CREATE TABLE IF NOT EXISTS grievance (
    id SERIAL PRIMARY KEY,
    gpscoordinates_longitude FLOAT,
    email VARCHAR(255),
    complaint_type TEXT,
    location TEXT,
    CreatedAt TIMESTAMP,
    title TEXT,
    citizenName TEXT,
    category TEXT,
    economicImpact TEXT,
    environmentalImpact TEXT,
    emotion TEXT,
    lastUpdatedDate TIMESTAMP,
    ResolutionTime TEXT,
    tehsil TEXT,
    complaintType TEXT,
    socialImpact TEXT,
    pincode VARCHAR(10),
    status TEXT,
    district TEXT,
    date TIMESTAMP,
    submissionDate TIMESTAMP,
    complaint TEXT,
    contactNumber VARCHAR(20),
    updatedAt TIMESTAMP,
    relatedPolicies TEXT,
    subcategory TEXT,
    urgencyLevel TEXT,
    ward TEXT,
    gpscoordinates_latitude FLOAT,
    isAnonymous BOOLEAN,
    estimated INT,
    departmentAssigned TEXT
);
