CREATE TABLE "Authority" (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL,
  level VARCHAR(50) NOT NULL,
  assignedRegion VARCHAR(255),
  jurisdiction VARCHAR(255),
  designation VARCHAR(255),
  departmentId VARCHAR(255),
  parentId VARCHAR(255),
  contactNumber VARCHAR(50),
  officeAddress TEXT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  isActive BOOLEAN DEFAULT TRUE,
  lastLogin TIMESTAMP,
  blockJurisdiction VARCHAR(255),
  panchayatArea VARCHAR(255),
  wardNumber VARCHAR(255),
  specialization VARCHAR(255),
  fieldArea VARCHAR(255),
  panchayatDetails JSONB,
  gramSabhaArea VARCHAR(255),
  villageCount INTEGER,
  panchayatWorkers JSONB,
  panchayatOfficers JSONB,
  FOREIGN KEY (parentId) REFERENCES "Authority"(id),
  FOREIGN KEY (departmentId) REFERENCES "Department"(id)
);